# Prediction - Inpatient Bed Utilization Above State-Year Threshold

## Import Dependencies

In [2]:
from datetime import datetime
import pandas as pd

## Load Data

In [3]:
df = pd.read_csv('data/covid_features_all_states_20200101_20251231.csv')

df.head()

         date state  ...  month_of_year  quarter_of_year
0  2020-01-01    AK  ...              1                1
1  2020-01-02    AK  ...              1                1
2  2020-01-03    AK  ...              1                1
3  2020-01-04    AK  ...              1                1
4  2020-01-05    AK  ...              1                1

[5 rows x 131 columns]

## Feature Engineering

In [4]:
df['date'] = pd.to_datetime(df['date'], format = '%Y-%m-%d')
df = df.sort_values(by=['state', 'date'])

df['date'].head()

0   2020-01-01
1   2020-01-02
2   2020-01-03
3   2020-01-04
4   2020-01-05
Name: date, dtype: datetime64[us]

In [5]:
df_stg = df[(df['date'] >= datetime(2020, 6, 1)) & (df['date'] <= datetime(2024, 4, 27))].reset_index(drop=True)

df_stg.head()

        date state  ...  month_of_year  quarter_of_year
0 2020-06-01    AK  ...              6                2
1 2020-06-02    AK  ...              6                2
2 2020-06-03    AK  ...              6                2
3 2020-06-04    AK  ...              6                2
4 2020-06-05    AK  ...              6                2

[5 rows x 131 columns]

In [6]:
df_stg = df_stg.set_index(['state','date'], drop=False)

df_stg.head()

                       date state  ...  month_of_year  quarter_of_year
state date                         ...
AK    2020-06-01 2020-06-01    AK  ...              6                2
      2020-06-02 2020-06-02    AK  ...              6                2
      2020-06-03 2020-06-03    AK  ...              6                2
      2020-06-04 2020-06-04    AK  ...              6                2
      2020-06-05 2020-06-05    AK  ...              6                2

[5 rows x 131 columns]

In [8]:
df_stg['rolling_average'] = df_stg['inpatient_beds_utilization'].rolling(7).mean()
df_stg['rolling_average_next_week'] = df_stg['rolling_average'].shift(-7)
df_stg['target_static'] = df_stg['rolling_average_next_week'] > 0.85
df_stg['target_static'] = df_stg['target_static'].astype('int')

/var/folders/sx/dymxkj2j1636xvkc7jyhyp840000gn/T/ipykernel_1973/3773379511.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_stg['target_static'] = df_stg['rolling_average_next_week'] > 0.85

In [9]:
df_stg['year'] = df_stg['date'].apply(lambda x: x.year)
df_int= df_stg.drop(columns=['state', 'date'])
means = df_int.groupby(by=['state','year']).mean()['inpatient_beds_utilization']
stds = df_int.groupby(by=['state','year']).std()['inpatient_beds_utilization']

/var/folders/sx/dymxkj2j1636xvkc7jyhyp840000gn/T/ipykernel_1973/1583589976.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_stg['year'] = df_stg['date'].apply(lambda x: x.year)

In [10]:
thresholds = means + 1.5*stds
thresholds

state  year
AK     2020    0.655930
       2021    0.762492
       2022    0.820945
       2023    0.782540
       2024    0.777631
                 ...
WY     2020    0.541928
       2021    0.534007
       2022    0.490789
       2023    0.478282
       2024    0.482329
Name: inpatient_beds_utilization, Length: 255, dtype: float64

In [11]:
thresholds_shifted = pd.DataFrame(thresholds.shift(1))

thresholds_shifted.columns = ['threshold']

thresholds_shifted

            threshold
state year
AK    2020        NaN
      2021   0.655930
      2022   0.762492
      2023   0.820945
      2024   0.782540
...               ...
WY    2020   0.843928
      2021   0.541928
      2022   0.534007
      2023   0.490789
      2024   0.478282

[255 rows x 1 columns]

In [12]:
df_int['state_'] = df_int.index.get_level_values(0)
df_int['date_'] = df_int.index.get_level_values(1)

df_mart = pd.merge(
    left = df_int,
    right = thresholds_shifted,
    how = "inner",
    on = ['state', 'year']
)

df_mart = df_mart.set_index(['state_', 'date_'], drop=False)

/var/folders/sx/dymxkj2j1636xvkc7jyhyp840000gn/T/ipykernel_1973/1280370851.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_int['state_'] = df_int.index.get_level_values(0)
/var/folders/sx/dymxkj2j1636xvkc7jyhyp840000gn/T/ipykernel_1973/1280370851.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_int['date_'] = df_int.index.get_level_values(1)
/var/folders/sx/dymxkj2j1636xvkc7jyhyp840000gn/T/ipykernel_1973/1280370851.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mart = pd.merge(

In [13]:
df_mart['target_dynamic'] = df_mart['rolling_average_next_week'] > df_mart['threshold']
df_mart['target_dynamic'] = df_mart['target_dynamic'].astype('int')

/var/folders/sx/dymxkj2j1636xvkc7jyhyp840000gn/T/ipykernel_1973/12590652.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_mart['target_dynamic'] = df_mart['rolling_average_next_week'] > df_mart['threshold']

In [55]:
df_mart['rolling_average_icu'] = df_mart['adult_icu_bed_utilization'].rolling(2).mean()

In [45]:
df_mart.head()

                   fb-survey_smoothed_wwearing_mask_7d  ...  rolling_average_icu
state_ date_                                            ...
AK     2020-06-01                                  NaN  ...                  NaN
       2020-06-02                                  NaN  ...                  NaN
       2020-06-03                                  NaN  ...                  NaN
       2020-06-04                                  NaN  ...                  NaN
       2020-06-05                                  NaN  ...                  NaN

[5 rows x 138 columns]

## Baseline Model

In [56]:
df = df_mart[df_mart['year']>2020]

df['baseline_prediction'] = df['rolling_average'] > df['threshold']
df['baseline_prediction'] = df['baseline_prediction'].astype('int')

/var/folders/sx/dymxkj2j1636xvkc7jyhyp840000gn/T/ipykernel_1973/715112114.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['baseline_prediction'] = df['rolling_average'] > df['threshold']

In [57]:
from sklearn.metrics import f1_score

baseline_f1 = f1_score(df['target_dynamic'],df['baseline_prediction'])

print(baseline_f1)

0.8082718171705936

## ARIMA

In [58]:
from statsmodels.tsa.arima.model import ARIMA

df_train = df[(df['state_'] == 'NC') & (df['year'] == 2023)]
df_test = df[(df['state_'] == 'NC') & (df['year'] > 2023)]

mod = ARIMA(endog=df_train['target_dynamic'], order=(1,0,0))

res = mod.fit()
preds = res.forecast(steps=len(df_test)).reset_index(drop=True)
preds = (preds > df_test['threshold'].reset_index(drop=True)).astype('int')

arima_f1 = f1_score(df_test['target_dynamic'], preds)

print(arima_f1)

0.5

/Users/johnwhendricks/miniforge3/envs/ds5003/lib/python3.14/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.
  self._init_dates(dates, freq)
/Users/johnwhendricks/miniforge3/envs/ds5003/lib/python3.14/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.
  self._init_dates(dates, freq)
/Users/johnwhendricks/miniforge3/envs/ds5003/lib/python3.14/site-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use one of the supported classes of index.
  self._init_dates(dates, freq)
/Users/johnwhendricks/miniforge3/envs/ds5003/lib/python3.14/site-packages/statsmodels/tsa/base/tsa_model.py:837: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_prediction_index(
/Users/johnwhendricks/miniforge3/envs/ds5003/lib/python3.14/site-packages/statsmodels/tsa/base/tsa_model.py:837: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.
  return get_prediction_index(

## Boosting

In [62]:
import xgboost as xgb

x_train = df_train[['adult_icu_bed_utilization', 'cases_roll_7', 'hhs_confirmed_admissions_covid_1d_prop_7dav']]
y_train = df_train['target_dynamic']
x_test = df_test[['adult_icu_bed_utilization', 'cases_roll_7', 'hhs_confirmed_admissions_covid_1d_prop_7dav']]
y_test = df_test['target_dynamic']

mod = xgb.XGBClassifier()

mod.fit(X = x_train, y = y_train)

preds = mod.predict(x_test)

xgb_f1 = f1_score(y_test, preds)

print(xgb_f1)

0.8571428571428571